services:
  blockchain:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"
    command:
      - "--host=0.0.0.0"
      - "--chain.chainId=31337"

  deployer:
    build: .
    depends_on:
      - blockchain
    environment:
      - HARDHAT_NETWORK=localhost
